# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-22 22:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('time', models.DateTimeField()),
                ('tag', models.CharField(blank=True, default='', max_length=100)),
                ('temperature', models.DecimalField()),
                ('humidity', models.DecimalField()),
                ('orientation', models.DecimalField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datapoints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
