# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fydp_server', '0002_auto_20170205_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='humidity',
            field=models.DecimalField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='temperature',
            field=models.DecimalField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
