# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fydp_server', '0003_auto_20170205_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='humidity',
            field=models.DecimalField(max_length=10),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='temperature',
            field=models.DecimalField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
