# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fydp_server', '0005_auto_20170205_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='humidity',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='temperature',
            field=models.CharField(max_length=10),
        ),
    ]
