# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fydp_server', '0006_auto_20170205_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_post_key',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
