# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fydp_server', '0008_auto_20170307_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='time',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
    ]
